Storehouse.Admin/Storehouse.Admin/Controllers/OtherSettingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Configuration;
using System.IO;
using System.Data.Entity;
using StorehouseAdmin.Models;
using Storehouse.Model;

namespace StorehouseAdmin.Controllers
{
    [Authorize(Roles = "Tenant")]
    public class OtherSettingsController : BaseController
    {
        //
        // GET: /HomePageSetting/
        StorehouseDBContext db = new StorehouseDBContext();
        string tenantId = string.Empty;

        public ActionResult Index()
        {
            db = new StorehouseDBContext();

            if (TempData["TenantId"] != null)
                tenantId = TempData["TenantId"].ToString();

            var homepagesettings = (from h in db.HomePageSettings
                                    where h.TenantId == tenantId
                                    select h).FirstOrDefault();

            if (homepagesettings == null)
            {
                return HttpNotFound();
            }
            ViewBag.Title = "Other Settings";
            return View(homepagesettings);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(HomePageSettings homepagesettings)
        {
            if (ModelState.IsValid)
            {
                db = new StorehouseDBContext();

                if (Request.Files["headerLogo"].ContentLength > 0)
                {
                    FileInfo headerlogo = new FileInfo(Request.Files["headerLogo"].FileName);
                    string webRootPath = Server.MapPath("~");

                    string headerlogoFilename = string.Concat(ConfigurationManager.AppSettings["UploadFilePath"], "Homepage/headerlogo", headerlogo.Extension);
                    Request.Files["headerLogo"].SaveAs(Server.MapPath(headerlogoFilename));
                    homepagesettings.HeaderLogo = headerlogoFilename;
                }

                if (Request.Files["footerLogo"].ContentLength > 0)
                {
                    FileInfo footerlogo = new FileInfo(Request.Files["footerLogo"].FileName);
                    string webRootPath = Server.MapPath("~");

                    string footerlogoFilename = string.Concat(ConfigurationManager.AppSettings["UploadFilePath"], "Homepage/footerlogo", footerlogo.Extension);
                    Request.Files["footerLogo"].SaveAs(Server.MapPath(footerlogoFilename));
                    homepagesettings.FooterLogo = footerlogoFilename;
                }

                db.Entry(homepagesettings).State = EntityState.Modified;
                db.SaveChanges();
            }
            return RedirectToAction("Index", "Home");
        }

    }
}

Storehouse.Admin/Storehouse.Admin/Views/OtherSettings/Index.cshtml
@model Storehouse.Model.HomePageSettings
@using (Html.BeginForm("Index", "OtherSettings", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="panel panel-default">
        <div class="panel-heading"><div class="panel-title"><h4>@ViewBag.Title</h4></div></div>

        <div class="panel-body">
            @Html.ValidationSummary(true)
            <div class="control-group">
                <div class="controls">
                    <label title="lblImage">Header Logo</label>
                    <img src="@Model.HeaderLogo" class="img-thumbnail" style="height:100px;width:100px;">
                    <input type="file" name="headerLogo" id="sliderImage" accept='image/*' />
                </div>
            </div>
            <div class="control-group">
                <div class="controls">
                    <label title="lblImage">Footer Logo</label>
                    <img src="@Model.FooterLogo" class="img-thumbnail" style="height:100px;width:100px;">
                    <input type="file" name="footerLogo" id="sliderBackground" accept='image/*' />
                </div>
            </div><br />
            <div class="control-group">
                <label title="lblImage">Slider Speed</label>
                <div class="controls">
                    @Html.TextBoxFor(model => model.SliderSpeed, new { @class = "form-control", @style = "width:20%" })
                    @Html.ValidationMessageFor(model => model.SliderSpeed)
                </div>
            </div><br />
            <div class="control-group">
                <label title="lblImage">Company Name</label>
                <div class="controls">
                    @Html.TextBoxFor(model => model.CompanyName, new { @class = "form-control", @style = "width:70%" })
                    @Html.ValidationMessageFor(model => model.CompanyName)
                </div>
            </div><br />
            <div class="control-group">
                <label title="lblImage">Company Phone Number</label>
                <div class="controls">
                    @Html.TextBoxFor(model => model.CompanyPhone, new { @class = "form-control", @style = "width:70%" })
                    @Html.ValidationMessageFor(model => model.CompanyPhone)
                </div>
            </div><br />
            <div class="control-group">
                <label title="lblImage">Company Email Address</label>
                <div class="controls">
                    @Html.TextBoxFor(model => model.CompanyEmail, new { @class = "form-control", @style = "width:70%" })
                    @Html.ValidationMessageFor(model => model.CompanyEmail)
                </div>
            </div><br />
            <div class="control-group">
                <label title="lblImage">Company Business Address</label>
                <div class="controls">
                    @Html.TextBoxFor(model => model.CompanyAddress, new { @class = "form-control", @style = "width:70%" })
                    @Html.ValidationMessageFor(model => model.CompanyAddress)
                </div>
            </div><br />
            <div class="control-group">
                <label title="lblImage">About Company</label>
                <div class="controls">
                    @Html.TextBoxFor(model => model.AboutCompany, new { @class = "form-control", @style = "width:70%" })
                    @Html.ValidationMessageFor(model => model.AboutCompany)
                </div>
            </div><br />
            <div class="control-group">
                <label title="lblImage">FAQs & TC</label>
                <div class="controls">
                    @Html.TextBoxFor(model => model.FAQsandTC, new { @class = "form-control", @style = "width:70%" })
                    @Html.ValidationMessageFor(model => model.FAQsandTC)
                </div>
            </div><br />
            <div class="control-group">
                <label title="lblImage">Events and Promos</label>
                <div class="controls">
                    @Html.TextBoxFor(model => model.EventsandPromos, new { @class = "form-control", @style = "width:70%" })
                    @Html.ValidationMessageFor(model => model.EventsandPromos)
                </div>
            </div><br />
            <div class="control-group">
                <label title="lblImage">ContactUs Email Host</label>
                <div class="controls">
                    @Html.TextBoxFor(model => model.ContactUsEmailHost, new { @class = "form-control", @style = "width:70%" })
                    @Html.ValidationMessageFor(model => model.ContactUsEmailHost)
                </div>
            </div><br />
            <div class="control-group">
                <label title="lblImage">ContactUs Email Port</label>
                <div class="controls">
                    @Html.TextBoxFor(model => model.ContactUsEmailPort, new { @class = "form-control", @style = "width:70%" })
                    @Html.ValidationMessageFor(model => model.ContactUsEmailPort)
                </div>
            </div><br />
            <div class="control-group">
                <label title="lblImage">ContactUs Email Recipient</label>
                <div class="controls">
                    @Html.TextBoxFor(model => model.ContactUsEmailRecipient, new { @class = "form-control", @style = "width:70%" })
                    @Html.ValidationMessageFor(model => model.ContactUsEmailRecipient)
                </div>
            </div><br />
            <div class="control-group">
                <div class="controls">
                </div>
            </div>
            <br />
            <div class="control-group">
                <div class="controls">
                    <a href="#saveChanges" data-toggle="modal" class="btn btn-default">Update</a>
                    @Html.ActionLink("Index", "Index", "Home")
                </div>
            </div>
        </div>
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.HeaderLogo)
        @Html.HiddenFor(model => model.FooterLogo)
        <div class="modal" id="saveChanges">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    </div>
                    <div class="modal-body">
                        <p>Are you sure you want to save changes in the other settings?</p>
                    </div>
                    <div class="modal-footer">
                        <input type="submit" value="Yes" class="btn btn-default" />
                        <a href="#" data-dismiss="modal" class="btn">No</a>
                    </div>
                </div><!-- /.modal-content -->
            </div><!-- /.modal-dalog -->
        </div><!-- /.modal -->
    </div>
}