Storehouse.Client/Storehouse.Client/Controllers/BrowseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Dynamic;
using CMSPortal.Models;
using Storehouse.Model;

namespace CMSPortal.Controllers
{
    public class BrowseController : BaseController
    {
        RobinsonsDBContext db = new RobinsonsDBContext();
        public ActionResult Articles(string id)
        {
            db = new RobinsonsDBContext();
            dynamic articles = new ExpandoObject();
            try
            {
                if (!string.IsNullOrEmpty(id))
                {
                    var template = (from t in db.Templates
                                    where t.Id == new Guid(id)
                                    select t).First();
                    articles.Template = template;

                    string templateId = template.Id.ToString();
                    var contents = from c in db.Contents
                                   where c.IsPublished == true && c.IsDeleted == false && c.TemplateId == templateId
                                   orderby c.PublishedDate descending
                                   select c;
                    articles.Contents = contents.ToList().AsEnumerable();
                }
            }
            catch
            {
                articles.Template = new Templates();
                articles.Contents = new Contents[] { new Contents() };
            }

            return View(articles);

        }

        public ActionResult RobinsonsStores(string id)
        {
            db = new RobinsonsDBContext();
            dynamic articles = new ExpandoObject();
            try
            {
                if (!string.IsNullOrEmpty(id))
                {
                    var template = (from t in db.Templates
                                    where t.Id == new Guid(id)
                                    select t).First();
                    articles.Template = template;

                    string templateId = template.Id.ToString();
                    var contents = from c in db.Contents
                                   where c.IsPublished == true && c.IsDeleted == false && c.TemplateId == templateId
                                   orderby c.PublishedDate
                                   select c;
                    articles.Contents = contents;

                }
            }
            catch
            {
                articles.Template = new Templates();
                articles.Contents = new Contents[] { new Contents() };
            }
            return View(articles);

        }
        public ActionResult FullArticle(string id)
        {
            db = new RobinsonsDBContext();
            dynamic fullarticle = new ExpandoObject();
            try
            {
                if (!string.IsNullOrEmpty(id))
                {
                    var content = (from c in db.Contents
                                   where c.Id == new Guid(id)
                                   select c).First();
                    fullarticle.Content = content;

                    var template = (from t in db.Templates
                                    where t.Id == new Guid(content.TemplateId)
                                    select t).First();
                    fullarticle.Template = template;
                }
            }
            catch
            {
                fullarticle.Template = new Templates();
                fullarticle.Content = new Contents();
            }
            return View(fullarticle);
        }
        public ActionResult Lists(string id)
        {
            db = new RobinsonsDBContext();
            dynamic lists = new ExpandoObject();
            try
            {
                if (!string.IsNullOrEmpty(id))
                {
                    var template = (from t in db.Templates
                                    where t.Id == new Guid(id)
                                    select t).First();
                    lists.Template = template;
                    string templateId = template.Id.ToString();
                    var contents = from c in db.Contents
                                   where c.IsPublished == true && c.IsDeleted == false && c.TemplateId == templateId
                                   orderby c.PublishedDate
                                   select c;
                    lists.Contents = contents;

                }
            }
            catch
            {
                lists.Template = new Templates();
                lists.Contents = new Contents[] { new Contents() };
            }
            return View(lists);

        }
        public ActionResult Collapsables(string id)
        {
            db = new RobinsonsDBContext();
            dynamic lists = new ExpandoObject();
            try
            {
                if (!string.IsNullOrEmpty(id))
                {
                    var template = (from t in db.Templates
                                    where t.Id == new Guid(id)
                                    select t).First();
                    lists.Template = template;
                    string templateId = template.Id.ToString();
                    var contents = from c in db.Contents
                                   where c.IsPublished == true && c.IsDeleted == false && c.TemplateId == templateId
                                   orderby c.PublishedDate
                                   select c;
                    lists.Contents = contents;

                }
            }
            catch
            {
                lists.Template = new Templates();
                lists.Contents = new Contents[] { new Contents() };
            }
            return View(lists);

        }
        public ActionResult Results(string Keywords)
        {
            dynamic lists = SearchKeyword(Keywords);
            ViewBag.Keywords = Keywords;
            ViewBag.Message = string.Format("Result(s) for {0}", Keywords);
            return View(lists);
        }
        [HttpPost]
        public ActionResult Results()
        {
            string Keywords = Request.Form["Keywords"].ToString();

            dynamic lists = SearchKeyword(Keywords);
            ViewBag.Keywords = Keywords;
            ViewBag.Message = string.Format("Result(s) for {0}", Keywords);
            return View(lists);
        }

        private dynamic SearchKeyword(string Keywords)
        {
            db = new RobinsonsDBContext();
            dynamic lists = new ExpandoObject();

            //dynamic resultcontent = new ExpandoObject();
            //List<dynamic> resultcontentsList = new List<dynamic>();
            //try
            //{
            //    if (!string.IsNullOrEmpty(Keywords))
            //    {
            //        var contents = from c in db.Contents
            //                       where c.IsPublished == true && c.IsDeleted == false
            //                       && (c.Name.Contains(Keywords) || c.Description.Contains(Keywords) || c.Markup.Contains(Keywords))
            //                       select c;
            //        foreach (Contents content in contents.ToList())
            //        {
            //            var template = (from t in db.Templates
            //                            where t.Id == new Guid(content.TemplateId)
            //                            select t).First();
            //            resultcontent.Id = content.Id;
            //            resultcontent.Name = content.Name;
            //            resultcontent.TemplateId = content.TemplateId;
            //            resultcontent.Type = template.Type;
            //            string description = string.Empty;
            //            if (content.Name.ToLower().Contains(Keywords.ToLower()))
            //                description = content.Name;
            //            else if (content.Description.ToLower().Contains(Keywords.ToLower()))
            //                description = content.Description;
            //            else if (content.Markup.ToLower().Contains(Keywords.ToLower()))
            //            {
            //                int index = content.Markup.ToLower().IndexOf(Keywords.ToLower());
            //                string substringdesc = description = content.Markup.Substring(index);
            //                if (substringdesc.Count() > 100)
            //                    description = substringdesc.Substring(0, 100);
            //                else
            //                    description = substringdesc;
            //            }
            //            resultcontent.Description = HttpUtility.HtmlDecode(description);
            //            resultcontentsList.Add(resultcontent);
            //        }
            //        lists.Contents = resultcontentsList.AsEnumerable();
            //    }

            try
            {
                if (!string.IsNullOrEmpty(Keywords))
                {
                    Keywords = Keywords.ToLower();

                    dynamic resultcontent = new ExpandoObject();
                    List<dynamic> resultcontentsList = new List<dynamic>();

                    var contents = from c in db.Contents
                                   where c.IsPublished == true && c.IsDeleted == false
                                   && (c.Name.ToLower().Contains(Keywords) || c.Description.ToLower().Contains(Keywords) || c.Markup.ToLower().Contains(Keywords))
                                   select c;

                    List<Contents> contentList = new List<Contents>();

                    foreach (Contents content in contents.ToList())
                    {

                        string substringdesc = content.Description;

                        if (substringdesc.Count() > 100)
                            substringdesc = substringdesc.Substring(0, 100);

                        content.Description = substringdesc;

Storehouse.Client/Storehouse.Client/Controllers/LearnMoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Dynamic;
using CMSPortal.Models;
using Storehouse.Model;

namespace CMSPortal.Controllers
{
    public class LearnMoreController : BaseController
    {
        RobinsonsDBContext db = new RobinsonsDBContext();
        //
        // GET: /LearnMore/
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Partners(string id)
        {
            db = new RobinsonsDBContext();
            var contents = from c in db.Contents
                           where c.TemplateId == id && c.IsDeleted == false
                           orderby c.PublishedDate descending
                           select c;

            List<dynamic> Partners = new List<dynamic>();
            foreach (Contents content in contents)
            {
                dynamic Partner = new ExpandoObject();
                Partner.Name = content.Name;
                Partner.Image = content.Image;
                Partner.Markup = HttpUtility.HtmlDecode(content.Markup);
                Partners.Add(Partner);
            }
            return View(Partners.AsEnumerable());

        }

        public ActionResult EventsAndPromos(string id)
        {
            db = new RobinsonsDBContext();
            var contents = from c in db.Contents
                           where c.TemplateId == id && c.IsDeleted == false
                           orderby c.PublishedDate descending
                           select c;

            List<dynamic> Events = new List<dynamic>();
            foreach (Contents content in contents)
            {
                dynamic Event = new ExpandoObject();
                Event.Id = content.Id;
                Event.Name = content.Name;
                Event.Description = content.Description;
                Event.Image = content.Image;
                Event.Markup = HttpUtility.HtmlDecode(content.Markup);
                Events.Add(Event);                           
            }
            return View(Events.AsEnumerable());

        }

        public ActionResult FAQAndTC(string id)
        {
            db = new RobinsonsDBContext();
            var contents = from c in db.Contents
                           where c.TemplateId == id && c.IsDeleted == false
                           orderby c.Sequence
                           select c;

            List<dynamic> Faqs = new List<dynamic>();
            foreach (Contents content in contents)
            {
                dynamic Faq = new ExpandoObject();
                Faq.Id = content.Id;
                Faq.Name = content.Name;
                Faq.Markup = HttpUtility.HtmlDecode(content.Markup);
                Faqs.Add(Faq);
            }
            return View(Faqs.AsEnumerable());

        }

	}
}

Storehouse.Client/Storehouse.Client/Views/LearnMore/EventsAndPromos.cshtml
@model IEnumerable<dynamic>
<!-- Page Title -->
<div class="section section-breadcrumbs">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>Events And Promos</h1>
            </div>
        </div>
    </div>
</div>

<div class="section">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="products-slider">
                    @foreach (dynamic item in Model)
                    {
                           <!-- Event Slider Item -->
                        <div class="shop-item">
                            <!-- Event Image -->
                            <div class="image">
                                <a href="page-product-details.html">
                                    <img src="@string.Concat(System.Configuration.ConfigurationManager.AppSettings["AdminPortal"], item.Image)" class="img-thumbnail" alt="@item.Name" />
                                </a>
                            </div>
                            <!-- Event Title -->
                            <div class="title">
                                <h3><a href="page-product-details.html">@item.Name</a></h3>
                            </div>
                            <!-- Event Price -->
                            <div class="price">
                                @item.Description
                            </div>
                            <!-- Read More Button -->
                            <div class="actions">
                                <a href="#" class="btn btn-small"><i class="icon-shopping-cart icon-white"></i>Read More</a>
                            </div>
                        </div>

                    <!-- End Event Slider Item -->
                    }
                </div>
            </div>
        </div>
    </div>
</div>

Storehouse.Client/Storehouse.Client/Views/LearnMore/FAQAndTC.cshtml
@model IEnumerable<dynamic>
<!-- Page Title -->
<div class="section section-breadcrumbs">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>Frequently Asked Questions</h1>
            </div>
        </div>
    </div>
</div>

<div class="section">
    <div class="container">
        <div class="row">
            <div class="col-md-12 faq-wrapper">
                <div class="panel-group" id="accordion2">
                    @foreach (dynamic item in Model)
                    {
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#@item.Id">
                                    @item.Name
                                </a>
                            </div>
                            <div id="@item.Id" class="accordion-body collapse">
                                <div class="accordion-inner">
                                    <div class="answer">Answer:</div>
                                    @Html.Raw(item.Markup)
                                </div>
                            </div>
                        </div>
                    }
                    <a href="@(Url.Action("Collapsables", "Browse", new { id = 0 }, null))">&laquo;Back</a>
                </div>
            </div>
        </div>
    </div>
</div>

Storehouse.Client/Storehouse.Client/Views/LearnMore/Partners.cshtml
@model IEnumerable<dynamic>

<!-- Page Title -->
<div class="section section-breadcrumbs">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>Partners</h1>
            </div>
        </div>
    </div>
</div>

<div class="section">
    <div class="container">
        @foreach (dynamic item in Model)
        {
            <div class="row service-wrapper-row">
                <div class="col-sm-4">
                    <div class="service-image">
                        <img src="@string.Concat(System.Configuration.ConfigurationManager.AppSettings["AdminPortal"], item.Image)" class="img-thumbnail" alt="@item.Name">
                    </div>
                </div>
                <div class="col-sm-8">
                    <h3>@item.Name</h3>
                    @Html.Raw(item.Markup)
                </div>
            </div>
        }
    </div>
</div>